### ISSUE TITLE
Saving the .opus file in-browser?

### ISSUE THREAD

**Issue by lepinsk** [Mido22/recordOpus#1]
Hey,

This is a really neat project! :+1: 

I've been playing around a bit with it, and I'm wondering if you have any idea how to save the opus encoded data in the browser, without uploading it to the server. I'm trying to produce a standalone `.opus` file without uploading, decoding to wav and then re-encoding. My goal is to output the same type of file as [opusenc.js](https://github.com/Rillke/opusenc.js), but with streaming input.

Any thoughts?

Thanks!

**Comment by Mido22** [comment]
@lepinsk sorry for replying this late, but I followed your advice, changed library to [opusenc.js](https://github.com/Rillke/opusenc.js), can you check the project now?
