### ISSUE TITLE
Server emit to all users

### ISSUE THREAD

**Issue by sdigihey** [Mido22/recordOpus#5]
When using server in multi user environment all users will receive each other emit events for finished recording. 
problem is in 

```
function returnLink(data, filepath){
    data.path = filepath;
    delete data.blob;
    io.emit('link', data);
} 
```

You are using io instance and it makes global emits, you should propagate each users socket instance and use it.

**Comment by johnnyvernin** [comment]
Hi sdigihey, thanks for your support, I have some problem, how I "propagate each users socket instance and use it." ? The Socket.io documentation don't cleared my mind :(

Thanks.

**Comment by Mido22** [comment]
updated code, added extra parameter (a callback function), now sockets reply to appropiate users alone, may be in future would change callbacks to promise :)

**Comment by johnnyvernin** [comment]
WOW, YOU'RE A HERO! Thanks a lot!!! I'am learning so much with your code! Best Regards from Brazil :D
